<!DOCTYPE html>
<html lang="en">
<head>
	<!-- Requires jQuery -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js" type="text/javascript"></script>

	<!-- Requires CodeMirror -->
	<script type="text/javascript" src="/js/editor/codemirror.js"></script>
	<link type="text/css" rel="stylesheet" href="/css/editor/codemirror.css" />

	<!-- Requires Mergely -->
	<script type="text/javascript" src="/js/editor/mergely.js"></script>
	<link type="text/css" rel="stylesheet" href="/css/editor/mergely.css" />
	
	<link href="/css/bootstrap.css" rel="stylesheet">
	<script type="text/javascript">

		$(document).ready(function () {
			$('#compare').mergely({
				width: 'auto',
				height: 'auto', // containing div must be given a height
				cmsettings: { readOnly: true },
			});
			
			var lhs_url =  '<?php echo $this->relativeLeftPath .  $this->path; ?>';
			var rhs_url =  '<?php echo $this->relativeRightPath . $this->path; ?>';
			
			$.ajax({
				type: 'GET', async: true, dataType: 'text',
				url: '/diff/get-content?path=' + lhs_url,
				success: function (response) {
					$('#path-lhs').text(lhs_url);
					$('#compare').mergely('lhs', response);
				}
			});
			$.ajax({
				type: 'GET', async: true, dataType: 'text',
				url: '/diff/get-content?path=' + rhs_url,
				success: function (response) {
					$('#path-rhs').text(rhs_url);
					$('#compare').mergely('rhs', response);
				}
			});
		});
	</script>
</head>
<body style="width:99%;">
    <div class="col-lg-12">
    	<div style="width:48%;float: left;word-wrap:break-word;">
    		<p style='text-align:center'>Path</p>
			<tt id="path-lhs"></tt>
		</div>
		<div style="width:48%;float: left;word-wrap:break-word;padding-left:4%;">
			<p style='text-align:center'>Path</p>
			<tt id="path-rhs"></tt>
		</div>
    </div>
    <br>
    

	<div id="mergely-resizer" style="height: 450px;">
		<div id="compare">
		</div>
	</div>

</body>
</html>