<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
 	<title>Branch Compare</title>

	<link rel="shortcut icon" href="data:image/x-icon;," type="image/x-icon">

    <!-- Bootstrap core CSS -->
    <link href="/css/bootstrap.css" rel="stylesheet">
    <!--external css-->
    <link href="/font-awesome/css/font-awesome.css" rel="stylesheet" />
    
    <!-- Custom styles for this template -->
    <link href="/css/style.css" rel="stylesheet">
    <link href="/css/style-responsive.css" rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="/css/easyui.css">
	<link rel="stylesheet" type="text/css" href="/css/easyuiicon.css">
	<link rel="stylesheet" type="text/css" href="/css/jquery.dataTables.css">
	<link rel="stylesheet" type="text/css" href="/css/custom.css">
	
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <div id="mask" style="width: 100%; height: 100%; display: block; opacity: 0.9; background-color: #000; z-index: 9000;  position: absolute; left: 0; top: 0;">
  	<p ><img style="width:100%;  margin-top:-10%" src="/img/load.gif"></p>
  </div>

  <section id="container" style="padding-bottom: 50px;">
      <!-- **********************************************************************************************************************************************************
      TOP BAR CONTENT & NOTIFICATIONS
      *********************************************************************************************************************************************************** -->
      <!--header start-->
      <header class="header black-bg">
            <!--logo start-->
            <a href="/compare" class="logo"><b>BRANCH COMPARE</b></a>
            <a id="svn-update" style="float:right" href="javascript:;"><img src="/img/update.png" class="img-circle" width="60"></a>
            <!--logo end-->
            <div class="col-lg-12"  style="padding-bottom:20px">
                <div class="row">
                	<div class="col-sm-2">
                    	<button id="refresh-data" class="btn btn-primary">Refresh</button>
                    </div>
                	<div class="col-sm-4" style="margin-top: 8px;" id="refresh-status">
            			<div class="refresh-msg">
    						<span class="label label-success"><?php if( true == $this->boolTrunk ) echo '<i class="glyphicon glyphicon-ok"></i> Trunk - Synced'; else echo '<i class="glyphicon glyphicon-remove"></i> Trunk - No Data';?></span>
    						<span class="label label-success"><?php if( true == $this->boolStage ) echo '<i class="glyphicon glyphicon-ok"></i> Stage - Synced'; else echo '<i class="glyphicon glyphicon-remove"></i> Stage - No Data';?></span>
    						<span class="label label-success"><?php if( true == $this->boolProd ) echo '<i class="glyphicon glyphicon-ok"></i> Prod - Synced'; else echo '<i class="glyphicon glyphicon-remove"></i> Prod - No Data';?></span>
						</div>
            			<div class="progress" style="display:none">
                          <div class="progress-bar progress-bar-striped active" role="progressbar" style="width: 0%">
                          </div>
                        </div>
                	</div>
                	
                	<div class="col-sm-5">
						<div class="btn-group">
							<button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								Compare Selected Files <span class="caret"></span>
							</button>
							<ul class="dropdown-menu">
								<li><a href="javascript:;" id="diff-ts"> Trunk & Staging - Mergley</a></li>
								<li><a href="javascript:;" id="diff-tp"> Trunk & Prod - Mergley</a></li>
								<li><a href="javascript:;" id="diff-sp"> Staging & Prod - Mergley</a></li>
	                            <?php if( true == $this->isWindows ) { ?>
									<li><a href="javascript:;" id="diff-ts-win"> Trunk & Staging - WinMerge</a></li>
                                  	<li><a href="javascript:;" id="diff-tp-win"> Trunk & Prod - WinMerge</a></li>
                                  	<li><a href="javascript:;" id="diff-sp-win"> Staging & Prod - WinMerge</a></li>
	                            <?php } ?>
                              </ul>
						</div>
                            
						<div class="btn-group">
							<button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    			Open In Beanstalk <span class="caret"></span>
							</button>
							<ul class="dropdown-menu">
								<li><a href="javascript:;" id="beanstalk-tr"> Trunk </a></li>
								<li><a href="javascript:;" id="beanstalk-st"> Staging</a></li>
								<li><a href="javascript:;" id="beanstalk-pr"> Prod</a></li>
							</ul>
						</div>
		
						<div class="btn-group">
							<button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								Highlight Diff <span class="caret"></span>
							</button>
							<ul class="dropdown-menu">
								<li><a href="javascript:;" id="light-tr"> Trunk </a></li>
								<li><a href="javascript:;" id="light-st"> Staging</a></li>
								<li><a href="javascript:;" id="light-pr"> Prod</a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
        </header>
      <!--header end-->
           
      <!-- **********************************************************************************************************************************************************
      MAIN CONTENT
      *********************************************************************************************************************************************************** -->
      <!--main content start-->
  
      <section id="main-content">
          <section class="wrapper">
			<?php echo $this->layout()->content; ?>
          </section>
      </section>

      <!--main content end-->
  </section>
     <!--footer start-->
  <footer class="site-footer">
      <div class="text-center">
          2015 - Powered by XAMPP
      </div>
  </footer>
      <!--footer end-->

    <!-- js placed at the end of the document so the pages load faster -->

    <script src="/js/jquery.js"></script>
    <script src="/js/jquery-1.8.3.min.js"></script>
    <script src="/js/bootstrap.min.js"></script>
    <script class="include" type="text/javascript" src="/js/jquery.dcjqaccordion.2.7.js"></script>
    <script src="/js/jquery.scrollTo.min.js"></script>
    <script src="/js/jquery.nicescroll.js" type="text/javascript"></script>
    <script type="text/javascript" src="/js/jquery.easyui.min.js"></script>


    <!--common script for all pages-->
    <script src="/js/common-scripts.js"></script>

	<script src="/js/jquery.ui.position.js" type="text/javascript"></script>
	<script src="/js/jquery.bt.min.js"></script>
	<script src="/js/jquery.dataTables.js"></script>
	
	<script src="/js/custom.js"></script>
		
  </body>
</html>